services:
  - type: web
    name: met4-api
    runtime: node
    rootDir: api
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: RESEND_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://yailia.github.io
